apiVersion: v1
kind: Service
metadata:
  name: scscf
  namespace: ims
spec:
  selector:
    io.kompose.service: scscf
  ports:
    - name: sip-udp
      protocol: UDP
      port: 5060
      targetPort: 5060
    - name: sip-tcp
      protocol: TCP
      port: 5060
      targetPort: 5060
    - name: udp-alt
      protocol: UDP
      port: 6060
      targetPort: 6060
    - name: tcp-alt
      protocol: TCP
      port: 6060
      targetPort: 6060
  type: ClusterIP
