apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../ims-diameter-deploy.yaml --out .
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: icscf
  name: icscf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: icscf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../ims-diameter-deploy.yaml --out .
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: icscf
    spec:
      containers:
        - args:
            - sleep
            - infinity
          env:
            - name: COMPONENT_NAME
              value: icscf
          image: default-route-openshift-image-registry.apps-crc.testing/ims/docker_kamailio:latest
          name: icscf
          volumeMounts:
            - mountPath: /var/log/kamailio
              name: icscf-logs
      restartPolicy: Always
      volumes:
        - name: icscf-logs
          persistentVolumeClaim:
            claimName: icscf-logs
