apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../ims-diameter-deploy.yaml --out .
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../ims-diameter-deploy.yaml --out .
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: open5gs
            - name: MYSQL_PASSWORD
              value: open5gs
            - name: MYSQL_ROOT_PASSWORD
              value: linux
            - name: MYSQL_USER
              value: open5gs
          image: mysql:8.0
          name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
