apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: scscf-logs
  name: scscf-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
