apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../ims-only-deploy.yaml --out .
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: icscf
  name: icscf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: icscf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../ims-only-deploy.yaml --out .
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: icscf
    spec:
      containers:
        - env:
            - name: COMPONENT_NAME
              value: icscf
          envFrom:
            - configMapRef:
                name: env
          image: default-route-openshift-image-registry.apps-crc.testing/ims/docker_kamailio:latest
          name: icscf
          volumeMounts:
            - mountPath: /mnt/icscf
              name: icscf-claim0
      restartPolicy: Always
      volumes:
        - name: icscf-claim0
          persistentVolumeClaim:
            claimName: icscf-claim0
