apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: diameter-logs
  name: diameter-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
